name: Bank Sampah

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Sesuaikan dengan versi PHP yang Anda gunakan
        extensions: mbstring, pdo, xml, bcmath

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Copy .env file
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Run database migrations
      run: php artisan migrate --force

    - name: Run the tests
      run: php artisan test

    - name: Deploy to Server via SSH
      if: github.ref == 'refs/heads/main'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
      run: |
        ssh -i $SSH_PRIVATE_KEY $REMOTE_USER@$REMOTE_HOST "cd /home/stmik-banksampah.neumediradev.my.id/public_html/API && git pull origin main && composer install --no-dev && php artisan migrate --force && php artisan cache:clear"
